# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 401ae1427e45e61c850d3ddc6408f74bfdfb99807b24c4359b25ca70589e267a729208d5556f531b2a6f8401f7226212ded1efc95f2744251eda314b0cfd289e

test:
  secret_key_base: c9261d24769c32fe38a053274db7048e0e855e3794542736e3ac11e17165291dff779c1e15f86d2fb69bc328cdf17b3517b9e15261200cf19a5482b91b1cc66b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
